import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 border-b-[1px]  border-gray-700">
          <ul className="flex gap-5 justify-center">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard/settings">Settings</Link>
            </li>
            <li>
              <Link href="/dashboard/analytics">Analytics</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
